server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/workmotion
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: employee
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      client-id: consumer-service
      max-poll-records: 1
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        request.timeout.ms: 300000
        heartbeat.interval.ms: 1000
        max.poll.interval.ms: 900000
        max.poll.records: 100
        session.timeout.ms: 600000
