version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  db:
    image: docker.io/postgres:13-alpine
    volumes:
      - "postgres_data:/workmotion"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workmotion

  consumer-service:
    image: com.workmotion/consumer-service:1.0-SNAPSHOT
    container_name: workmotion-consumer
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - db
    environment:
      - "SPRING_PROFILES_ACTIVE=doc"

  producer-service:
    image: com.workmotion/producer-service:1.0-SNAPSHOT
    container_name: workmotion-producer
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - consumer-service
    environment:
      - "SPRING_PROFILES_ACTIVE=doc"
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgres_data:
    driver: local
